### ISSUE TITLE
Use keys from code behind

### ISSUE THREAD

**Issue by PhilipHuston** [rhyous/WPFSharp.Globalizer#10]
How can I access a key of a GlobalizationResourceDictionary from code behind? And if I set for example the text of a button from code behind, does it still changes the language if the user changes the language through the combobox?

I tried accessing a key the following way:

`foreach (ResourceDictionary dic in GlobalizedApplication.Instance.GlobalizationManager.MergedDictionaries)
{
      if (dic.GetType() == typeof(GlobalizationResourceDictionary))
      {
             mCurrentLanguageDic = (GlobalizationResourceDictionary)dic;
      }
}
string s = (string)mCurrentLanguageDic["MyKey"];
`

This works, but when I change the language through the combobox the language doesn't change.

Can somebody give me a hint?
Thanks...

**Comment by Awsmolak** [comment]
If you are setting the text of a button in code behind, that is different than _binding_ and updates will not happen automatically. Every time the string changes you will have to manually reset that buttons text from code behind. 

You can subscribe to an event that fires when the language is changed like this:
```
var glApp = CommonUI.App.Current as GlobalizedApplication;
glApp.GlobalizationManager.ResourceDictionaryChangedEvent  += (source, args) => 
{
     //do something in response to language change here

     //fire property notification to update bindings
     NotifyPropertyChanged(string.Empty);
};
```
See this thread for osme more details:
https://github.com/rhyous/WPFSharp.Globalizer/issues/6

Also, you should be able to use this code to find your globalized strings or resources, without having to search and match the chosen language:

`string s = (string)Application.Current.FindResource("resourceKey");`

**Comment by PhilipHuston** [comment]
Thank You! I will do it like this.
