### ISSUE TITLE
Handle XamlReader.Load Exceptions

### ISSUE THREAD

**Issue by lablabla** [rhyous/WPFSharp.Globalizer#3]
Hi,

If there is an issue with the language XAML file (for example, multiple strings with the same key), a `XamlParseException` is thrown when `LoadFromFile` is called.
try..catching the call to `SwitchLanguage` doesn't work. 

This cause the entire program to crash. I would have expected in such case the the language will not be loaded into the `AvailableLanguages`, or maybe some other solution that would not result in a complete crash.

Thanks. Great project.

**Comment by rhyous** [comment]
Interesting. You added try/catch and it didn't catch? I just tried and it did catch the exception.

https://github.com/rhyous/WPFSharp.Globalizer/commit/614556363dd399ca533b34debe8e4595b74e618d

**Comment by contagion** [comment]
I've tried your latest update on this issue and it works great.
Malformed XAML file and non-exist languages will not cause the entire program to crash anymore.  

Would you be so kind to also update the nuget package ?

Thanks for the great project.

**Comment by rhyous** [comment]
I just published a new version of the NuGet package

**Comment by rhyous** [comment]
Please confirm the NuGet package is working and I will close this issue.
