### ISSUE TITLE
Small re-formatting error in samples

### ISSUE THREAD

**Issue by JohannStudanski** [rhyous/WPFSharp.Globalizer#4]
The parenthesis seem to be reformatted badly when switching to Hebrew (Both examples in WPFSharp.Globalizer solution)
![Image of screen in Hebrew](https://s31.postimg.org/3kxppiirv/Hebraeisch.png)

**Comment by rhyous** [comment]
How did I never notice that before? I'll take a look.

**Comment by rhyous** [comment]
Looks like this is just what WPF does. I'll hunt for a way to work around this flaw.
http://stackoverflow.com/questions/7045676/wpf-how-does-flowdirection-righttoleft-change-a-string

**Comment by rhyous** [comment]
@JohannStudanski 
I made these controls localizable with the latest check-in. So Hebrew now localizes and doesn't look wrong.
https://github.com/rhyous/WPFSharp.Globalizer/commit/bd9b611479793c8db086c6775ac485311a754770

**Comment by rhyous** [comment]
@JohannStudanski Do you have further questions? Or should I close this issue out?

**Comment by JohannStudanski** [comment]
Sorry, didn't log in to GitHub for quite some time, and the email client marked the github messages as spam. Thanks for taking care of it!
