### ISSUE TITLE
DesignTimeResources.xaml must be located in folders Properties

### ISSUE THREAD

**Issue by LukeOwncloud** [rhyous/WPFSharp.Globalizer#5]
I took me some time to realize why to realize why the Designer would not display globalized resources, even though auto-completion worked fine. Also running the application was not a problem.

The problem: I included `DesignTimeResources.xaml` from a different folder. Moving the file to folder `Properties` and changing the project file accordingly fixed the problem.

**Comment by Awsmolak** [comment]
Thanks! I ran into this problem too. I copied the one from the example MVVM project. It should be easy enough to include this when installing the package from NuGet....Or it should be mentioned in `readme.md`

**Comment by rhyous** [comment]
Added Readme.
Added to NuGet 1.0.6
